GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"testing post api",
    "important":true,
    "date":null
}

###
PUT http://localhost:3001/api/notes/10
Content-Type: application/json

{
    "content":"testing post api",
    "important":false,
    "date":null
}

###
DELETE http://localhost:3001/api/notes/5